baseURL = "https://oboegaki.pages.dev"
copyright = "No Copyright"
title = "oboegaki"
#paginate = 10
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This settings allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  #quality = 75

[params]
  # dark or light, defaults to light
  #defaultTheme = "light"
  # gray red green yellow blue purple aqua orange, defaults to blue
  #themeColor = "blue"
  # soft medium hard, defaults to medium
  #themeContrast = "medium"
  author = "pettyblue@proton.me"
  subtitle = "my notes."
  description = "Memorandum. I write about tech."

  [params.logo]
    text = "oboegaki"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "bash",
      "diff",
      "toml",
      "lua"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 100 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 100

  # Social share links for posts:
  #   - iconSuite: "simple-icon" or "tabler-icon"
  #   - iconName: name of the icon from the "iconSuite"
  #   - {url} placeholder for post .Permalink
  #   - {title} placeholder for post .Title
  # See  https://github.com/bradvin/social-share-urls for more format strings
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "simple-icon"
    iconName = "telegram"
    formatString = "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    iconSuite = "tabler-icon"
    iconName = "mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
